version: '3.9'

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    restart: always
    # by using volumes,
    # it means that we can have consistent database even if we destroy and recreate our service
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      # 這裡的static-data和app的volumes的static-data一樣, 為shared volume
      # this is how the proxy is able to serve the static files without bothering the application(python code)
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data: