# Generated by Django 3.2.6 on 2022-04-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
